In [ ]:
# array object in numpy is called ndarray.
# PIP is a package that installs and manages Python packages.
# PIP: PIP Installs Packages

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5]) # list is passed as an argument
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

* a is an numpy array object

In [ ]:
print(np.__version__) # __version__ -> attribute
# The version string '2.1.0' is stored under __version__ attribute.

2.1.0


In [ ]:
a = np.array((1, 2, 3, 4, 5)) # # tuple is passed as an argument
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

* In NumPy, the dimension of an array refers to the number of axes (also called ranks) along which data is organized. It determines how many indices are needed to access elements in the array.



In [ ]:
# 0D Arrays / Scalars
a = np.array(10)
print(a, a.ndim, a.shape)

10 0 ()


In [ ]:
# 1D Arrays / uni-dimensional arrays / Vector
a = np.array([10, 20, 30, 40, 50])
print(a, a.ndim, a.shape)

[10 20 30 40 50] 1 (5,)


In [19]:
# 2D Arrays / Matrix / 2nd Order Tensors
a = np.array([[10, 20], [30, 40], [50, 60]]) # 3 rows & 2 cols
print(a)
print(a.ndim, a.shape)

[[10 20]
 [30 40]
 [50 60]]
2 (3, 2)


In [21]:
# 3D Arrays / Tensor-like structure
a = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(a)
print(a.ndim, a.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3 (2, 2, 3)


* (depth, rows, cols)

In [22]:
# Higher-Dimensional Arrays: NumPy supports arrays with more than 3 dimensions, 
# useful in deep learning, image processing, etc.

a = np.array([[[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]])
print(a)
print(a.ndim, a.shape)

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4 (1, 2, 2, 3)


NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [23]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# An array can have any number of dimensions, When the array is created, 
# you can define the number of dimensions by using the `ndmin` argument.
# ndmin argument in NumPy stands for "minimum number of dimensions"

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

In [32]:
arr = np.array([10,20,30,40,50])
print(arr[1])
print(arr[4])
print(arr[1] + arr[4])

20
50
70


In [ ]:
### Access 2D Arrays

## To access elements from 2-D arrays we can use comma separated integers representing the 
# dimension and the index of the element.
## Think of 2-D arrays like a table with rows and columns, where the dimension represents 
# the row and the index represents the column.

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
### Access 3D Arrays

## To access elements from 3-D arrays we can use comma separated integers representing
# the dimensions and the index of the element.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # { 0: depth, 1: row, 2: coln }

6


In [ ]:
# Explanation

''' 
Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

'''


In [ ]:
## Negative Indexing
# Use negative indexing to access an array's element from the end.

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# Ques: Print the last element from the 2nd dim 
# Ans: 2nd dimension is [6,7,8,9,10]
print(arr[1,4]) # positive indexing
print(arr[1,-1]) # negative indexing 

10
10


In [ ]:
# Slicing Arrays: [start, end, step] ; default values => 0, len(arr), 1 
# start is included but end is excluded

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [4]:
# Negative Slicing
arr = np.array([1,2,3,9,87,65,4])
print(arr[-3:-1]) # slice from the index 3 from the end to index 1 from the end

[87 65]


In [5]:
# Slicing 2D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
# Ques: From both elements, return index 2

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[:,2]) # or print(arr[0:2,2])

[3 8]
[3 8]


In [8]:
# Ques: From both elements, slice index 1 to index 4 (not included)

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[:,1:4])

[[2 3 4]
 [7 8 9]]


#### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [10]:
arr = np.array([1,2,3,4,5])
# The NumPy array object has a property/attribute called dtype that returns the data type of the array:
print(arr, arr.dtype)

[1 2 3 4 5] int64


In [12]:
arr = np.array(['apple', 'banana', 'mango', 'watermelon'])
print(arr, arr.dtype)

['apple' 'banana' 'mango' 'watermelon'] <U10


<U10:
* <: Indicates byte order (Little-endian, though it's not very relevant for strings).
* U: Represents a Unicode string data type in NumPy.
* 10: Specifies the maximum string length in characters (including null terminators if needed).

In [16]:
## We use the array() function to create arrays, this function can take an optional argument: 
# `dtype` that allows us to define the expected data type of the array elements

arr = np.array([1, 2, 32, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'32' b'4']
|S2


* The b'' notation indicates that the values are byte strings.
* |S2 means byte string of length 2.

In [18]:
# Ques: Create an array with data type 4 bytes integer:

arr = np.array([10,20,30], dtype='i4')
print(arr, arr.dtype)

[10 20 30] int32


ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [19]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

Base 10 means the decimal number system, which includes digits 0 to 9.

In [ ]:
# Converting Data Type on Existing Arrays: astype() method - converts the array as a specific data type.
a1 = np.array([1.5,2.4,13.8,4.75,5.98])
print(a1)
print('data type of a1:', a1.dtype)
a2 = a1.astype('i') # passing i in quote as argument
print(a2)
print('data type of a2:', a2.dtype)

[ 1.5   2.4  13.8   4.75  5.98]
data type of a1: float64
[ 1  2 13  4  5]
data type of a2: int32


In [ ]:
a1 = np.array([1.5,2.4,13.8,4.75,5.98])
print(a1)
print('data type of a1:', a1.dtype)
a2 = a1.astype(int) # passing int keyword as argument
print(a2)
print('data type of a2:', a2.dtype)

In [27]:
a1 = np.array([1,0.0,3,0,5])
print(a1)
print('data type of a1:', a1.dtype)
a2 = a1.astype(bool) 
print(a2)
print('data type of a2:', a2.dtype)

[1. 0. 3. 0. 5.]
data type of a1: float64
[ True False  True False  True]
data type of a2: bool


#### Copy vs View

In [40]:
# copy
a = np.array([10,20,25,40,56])
print('a =',a)
b = a.copy()
print('b =',b)

a[1] = 80

print('a =',a)
print('b =',b)

a = [10 20 25 40 56]
b = [10 20 25 40 56]
a = [10 80 25 40 56]
b = [10 20 25 40 56]


In [41]:
# view
a = np.array([10,20,25,40,56])
print('a =',a)
b = a.view()
print('b =',b)

a[1] = 80

print('a =',a)
print('b =',b)

a = [10 20 25 40 56]
b = [10 20 25 40 56]
a = [10 80 25 40 56]
b = [10 80 25 40 56]


In [42]:
# Ques: Make a view, change the view, and display both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


- copies owns the data, and views does not own the data

In [ ]:
# Every NumPy array has the attribute `base` that returns None if the array owns the data.
# Otherwise, the `base` attribute refers to the original object.

arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base) # copy owns the data, return None
print(y.base) # view doesn't owns the data, return the original array i.e., arr

None
[1 2 3 4 5]


#### Shape of an Array
The shape of an array is the number of elements in each dimension.

In [45]:
## NumPy arrays have an attribute called `shape` that returns a tuple with each index having 
# the number of corresponding elements.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [46]:
## Ques: Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 
# and verify that last dimension has value 4

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


At index-4, we have value 4, so we can say that 5th (4+1th) dimension has 4 elements.

In [47]:
## What does the shape tuple represent?
# Integers at every index tells about the number of elements the corresponding dimension has.

#### NumPy Array Reshaping

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [ ]:
# reshaping from 1D to 2D: reshape()

## Ques: Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
# reshaping from 1D to 3D: reshape()

## Ques: Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(2,3,2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
# Ques: Can we reshape into any shape?
# Ans: Yes, as long as the elements required for reshaping are equal in both shapes.

''' 
    We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot 
    reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
'''

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [ ]:
# Ques: Check if the returned array is a copy or a view: using `base` attribute

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
print(newarr)

print(newarr.base) # returns the original array => view

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


- We are allowed to have one "unknown" dimension, pass -1 as the value, and NumPy will calculate this number for you.

In [59]:
# Ques: Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2,2,-1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Note: We can not pass -1 to more than one dimension.

##### Flattening the arrays

* Flattening array means converting a multidimensional array into a 1D array: using reshape(-1)

In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


Note: 

    There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. 

These fall under Intermediate to Advanced section of numpy.

##### Iterating NumPy Array 

In [ ]:
# iterating 1D Array: It will go through each element one by one
arr = np.array([1,2,3,4,5])
for n in arr:
    print(n, end=' ')

1 2 3 4 5 

In [8]:
# iterating 2D Array: It will go through all the rows
arr = np.array([[1,2,3],[4,5,6]])
for n in arr:
    print(n)

[1 2 3]
[4 5 6]


Note: If we iterate on a n-D array it will go through $(n-1)^\text{th}$ dimension one by one.

In [12]:
# Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
for a in arr:
    for n in a:
        print(n)

1
2
3
4
5
6


In [13]:
# iterating 3D Array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [15]:
# iterating the array in each dimensions to return the scalar values

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for a in arr:
    for b in a:
        for n in b:
            print(n)
            


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating Arrays Using nditer() method

## Ques: Iterate through the following 3-D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for n in np.nditer(arr):
    print(n)

1
2
3
4
5
6
7
8


In [7]:
arr = np.array([1,2,3,4,5])

for n in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(n)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')


In the numpy.nditer() method, the argument op_dtypes stands for "operand data types".

op_dtypes is used to set the expected output data type.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [9]:
# Ques: Iterate through every scalar element of the 2D array skipping 1 element
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for n in np.nditer(arr[:,::2]):
    print(n)

1
3
5
7


In [11]:
## Enumerated Iteration Using ndenumerate()

# Enumeration means mentioning sequence number of somethings one by one.
# ndenumerate() method can be used to get corresponding index of the element while iterating.


In [12]:
# Ques: Enumerate on following 1D arrays elements
arr = np.array([1, 2, 3])

for idx, n in np.ndenumerate(arr):
    print(idx, n)

(0,) 1
(1,) 2
(2,) 3


In [13]:
# Ques: Enumerate on following 1D arrays elements
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, n in np.ndenumerate(arr):
    print(idx, n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#### Joining NumPy Arrays

* Joining means putting contents of two or more arrays in a single array.
* In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. 
* If axis is not explicitly passed, it is taken as 0.

In [ ]:
a = np.array([1, 2, 3])
print(f'a = {a} & data type of a: {a.dtype}')
b = np.array([4, 5, 6])
print(f'b = {b} & data type of b: {b.dtype}')
print(np.concatenate((a,b)), np.concatenate((a,b)).base) # copy since it owns the data

a = [1 2 3] & data type of a: int64
b = [4 5 6] & data type of b: int64
[1 2 3 4 5 6] None


    Concept of Axis in a NumPy Array
In NumPy, the axis represents the dimensions along which operations are performed. It helps in understanding how functions like sum(), mean(), concatenate(), etc., behave.

    Axes are defined for arrays with more than one dimension. 
A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).


\[
\begin{array}{|c|c|c|c|}
\hline
\textbf{Array} & \textbf{axis 0} & \textbf{axis 1} & \textbf{axis 2} \\
\hline
\text{1D} & \text{Only axis 0} & N/A & N/A \\
\hline
\text{2D} & Downward (↓ rows) & Sideways (→ columns) & N/A \\
\hline
\text{3D}  & \text{Across depth (↗)} & \text{Across rows} & \text{Across columns} \\
\hline
\end{array}
\]






In [ ]:
# Ques: Join two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2), axis=0)) # or np.concatenate((arr1, arr2)) since default axis is 0


[1 2 3 4 5 6]


In [ ]:
# Ques: Join two 2-D arrays horizontally (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((arr1,arr2), axis=0)) # vertically
print(np.concatenate((arr1,arr2), axis=1)) # horizontally


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


##### Joining Arrays Using Stack Functions